---
ansible_pwd: "{{ lookup('env', 'PWD') }}"
workspace: "{{ lookup('env', 'WORKSPACE') }}"
project_terraform_dir: "{{ ansible_pwd }}/terraform"

group_vars_dir: "{{ ansible_pwd }}/group_vars"

workspace_host_vars_dir: "{{ ansible_pwd }}/host_vars"
workspace_group_vars_dir: "{{ group_vars_dir }}/{{ workspace }}_platform"
workspace_terraform_dir: "{{ workspace_group_vars_dir }}/terraform"
workspace_secrets_dir: "{{ workspace_group_vars_dir }}/secrets"

host_vars_dir: "{{ workspace_host_vars_dir }}/{{ inventory_hostname }}"
host_secrets_dir: "{{ host_vars_dir }}/secrets"

workspace_default_ssh_private_key_file: "{{ workspace_secrets_dir }}/{{ workspace }}.key"
workspace_default_ssh_public_key_file: "{{ workspace_default_ssh_private_key_file }}.pub"

local_ca_private_key: "{{ workspace_secrets_dir }}/ca.cert.key"
local_ca_certificate: "{{ workspace_secrets_dir }}/ca.cert.pem"

host_private_key_passphrase_file: "{{ host_secrets_dir }}/self.cert.pass"
host_private_key_passphrase: "{{ lookup('password', host_private_key_passphrase_file + ' length=42') }}"
host_private_key: "{{ host_secrets_dir }}/self.cert.key"
host_certificate: "{{ host_secrets_dir }}/self.cert.pem"
host_fullchain_certificate: "{{ host_secrets_dir }}/self.fullchain.cert.pem"

local_ca_passphrase: "{{ lookup('password', workspace_secrets_dir + '/local_ca.passphrase length=42') }}"
local_ca_common_name: "{{ workspace }} Internal CA"
bootstrap_ssh_PermitRootLogin: "no"    # noqa var-naming
required_system_packages:
  - apt-transport-https
  - aptitude
  - build-essential
  - git
  - libffi-dev
  - libperl-dev
  - libssl-dev
  - python3
  - python3-apt
  - python3-distutils-extra
  - python3-venv
  - python3-pip
  - python3-setuptools
  - python-apt-dev
  - sudo
