- name: Install
  include_tasks: install.yml
  tags:
    - install

- name: Configure
  include_tasks: configuration.yml
  tags:
    - config

- name: Make sure nomad service is running
  systemd:
    name: nomad
    daemon_reload: true
    state: started
    enabled: true
