---
- name: First node init
  include_tasks: vault_init.yml
  run_once: true
  tags:
    - config

- name: Read raw vault status
  command: >-
    vault status -format json -address={{ vault_api_protocol }}://{{ vault_api_address }}:{{ vault_api_port }}
  register: _vault_status_results
  changed_when: false
  failed_when: _vault_status_results.rc == 1
  until: (_vault_status_results.stdout | from_json).initialized
  retries: 9
  delay: 10
  tags: config

- name: Set unseal target
  set_fact:
    vault_unseal_target: "{{ [groups[vault_inventory_masters_group][0]] }}"

- name: Unseal first node
  include_tasks: vault_unseal.yml

- name: Read raw vault status
  command: >-
    vault status -format json -address={{ vault_api_protocol }}://{{ vault_api_address }}:{{ vault_api_port }}
  register: _vault_status_results
  changed_when: true
  when: inventory_hostname != groups[vault_inventory_masters_group][0]
  failed_when: _vault_status_results.rc == 1
  until: (_vault_status_results.stdout | from_json).initialized
  retries: 9
  delay: 10

- set_fact:
    vault_unseal_target: "{{ groups[vault_inventory_masters_group][1:] }}"

- name: Unseal every other nodes
  include_tasks: vault_unseal.yml
  when: inventory_hostname != groups[vault_inventory_masters_group][0]
