---
- name: Add hashicorp apt key.
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
    validate_certs: true

- name: Add hashicorp repo into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com bullseye main
    state: present

- name: Install common packages
  apt:
    name: "vault={{ vault_version }}"
    state: present

- name: Pin vault release
  copy:
    dest: /etc/apt/preferences.d/vault
    mode: 0644
    content: |
      Package: vault
      Pin: version {{ vault_version }}
      Pin-Priority: 1002

- name: Create vault configuration directory
  file:
    path: /etc/vault.d
    mode: 0755
    state: directory

- name: Check directories exist
  file:
    path: "{{ _current_expected_dir }}"
    owner: vault
    group: vault
    state: directory
    mode: 0700
  loop: "{{ vault_expected_directories }}"
  loop_control:
    loop_var: _current_expected_dir

- name: Common private ssl directory
  file:
    path: "{{ vault_tls_dir }}"
    owner: root
    group: ssl-cert
    state: directory
    mode: 0750

- name: Add vault to ssl-cert group
  user:
    name: vault
    groups: ssl-cert
    append: true

- name: Upload CA certificate
  copy:
    src: "{{ vault_local_ca_cert }}"
    dest: "{{ vault_ca_certificate }}"
    owner: root
    group: ssl-cert
    mode: 0644
  notify: Update ca trust
  when: vault_use_custom_ca

- name: Flush
  meta: flush_handlers

- name: Upload self certificate
  copy:
    src: "{{ _current_cert_part }}"
    dest: "{{ vault_tls_dir }}/{{ _current_cert_part.split('/')[-1] }}"
    owner: root
    group: ssl-cert
    mode: 0640
  loop:
    - "{{ vault_node_cert }}"
    - "{{ vault_node_cert_private_key }}"
    - "{{ vault_node_cert_fullchain }}"
  loop_control:
    loop_var: _current_cert_part
  notify: restart vault

# TODO
# sudo setcap cap_ipc_lock=+ep $(readlink -f $(which vault))
# https://docs.ansible.com/ansible/latest/collections/community/general/capabilities_module.html
