---
- include_tasks: "vault_status.yml"
  tags: config

- block:
    - name: Node initialization
      command: >-
        vault operator init -format json -address={{ vault_api_protocol }}://{{ vault_api_address }}:{{ vault_api_port }}
      register: _vault_init_results

    - name: Store vault init keys
      copy:
        dest: "{{ workspace_secrets_dir }}/unseal.yml"
        mode: 0600
        content: |-
          ---
          {{ _vault_init_results.stdout | from_json | to_nice_yaml }}
      become: false
      delegate_to: localhost

    - include_tasks: "vault_status.yml"
  when:
    - not _vault_status.initialized
  tags:
    - config
