---
- name: Cook variable
  set_fact:
    _local_resolver_platform_zone: >-
      {{
        _local_resolver_platform_zone
        | default({})
        | combine({ (_current_host): {'ipv4': hostvars[_current_host].ansible_default_ipv4.address } })
      }}
  loop: "{{ _local_resolver_platform_inventory_names }}"
  loop_control:
    loop_var: _current_host

- name: Install unbound
  apt:
    name: unbound

- name: Apparmoring the right to log
  lineinfile:
    path: "/etc/apparmor.d/local/usr.sbin.unbound"
    create: true
    mode: 0644
    line: >-
      /var/log/unbound/unbound.log rw,
  notify: Reload apparmor

- name: Override dns autoconf
  lineinfile:
    path: /etc/dhcp/dhclient.conf
    line: "{{ _current_dhclient_config_line }}"
  loop:
    - >-
      prepend domain-search "{{ local_resolver_domain }}";
    - >-
      prepend domain-name-servers 127.0.0.1;
  loop_control:
    loop_var: _current_dhclient_config_line
  notify: Restart networking

- name: Statically configure unbound
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf.d/local-resolver.conf
    mode: 0644
  notify: Restart unbound

- name: Enable unbound service
  systemd:
    name: unbound
    state: started
    enabled: true
