---
- hosts: localhost
  become: false
  gather_facts: false

  vars:
    tf_module_name: "consul_config"

  pre_tasks:
    - name: Load group vars
      include_vars:
        dir: "{{ hs_workspace_group_vars_dir }}"
        ignore_unknown_extensions: true

  tasks:
    - name: Validate API avalability
      uri:
        url: "https://{{ consul_public_cluster_address }}:8501/v1/agent/members"
        headers:
          X-Consul-Token: "{{ root_consul.SecretID }}"
      register: _consul_ping_api
      until: _consul_ping_api.status == 200
      retries: 30
      delay: 10

    - name: "Copy terraform sources"
      copy:
        src: "{{ tf_module_src }}"
        dest: "{{ tf_module_dest }}"
        mode: "u+rwX,g+rX,o-rX"

    - name: "COMMON - Do Terraform (can take up to 30 minutes)"
      community.general.terraform:
        project_path: "{{ tf_module_dest }}"
        state: "{{ (tf_action == 'destroy') | ternary('absent', 'present') }}"
        force_init: true
        workspace: "{{ hs_workspace }}"
        variables:
          consul_address: "hs.{{ public_domain }}:{{ consul_api_port }}"
          datacenter: "{{ hs_workspace }}"
          token: "{{ root_consul.SecretID }}"
      register: tf_result

    - name: Generate host_vars for public_ns
      copy:
        dest: "{{ hs_workspace_secrets_dir }}/tf_consul_config.yml"
        mode: 0600
        content: |-
          ---
          consul_connect_token_server: "{{ tf_result.outputs.consul_acl_nomad_server_token.value }}"
          consul_connect_token_client: "{{ tf_result.outputs.consul_acl_nomad_client_token.value }}"
