---
- hosts: "{{ lookup('env', 'WORKSPACE') }}_platform"
  become: false
  gather_facts: false

  tasks:
    - setup:
      until: "{{ (ansible_all_ipv4_addresses | length) == 2 }}"

    - set_fact:
        private_ip: >-
          {{ (ansible_all_ipv4_addresses | difference([ansible_default_ipv4.address]))[0] }}

    - name: Set ssh user to correct value
      set_fact:
        current_ssh_user: "root"
        controller_ipv4: "{{ hostvars['gamma-controller'].public_ipv4 }}"
        ssh_private_key_file: "{{ workspace_default_ssh_private_key_file }}"

    - set_fact:
        masters_ipv4: >-
          {{
            masters_ipv4 | default([]) | union([hostvars[item].private_ip])
          }}
      loop: >-
        {{ groups['gamma_masters'] }}


    - set_fact:
        minions_ipv4: >-
          {{
            minions_ipv4 | default([]) | union([hostvars[item].private_ip])
          }}
      loop: >-
        {{ groups['gamma_minions'] }}

    - name: Set correct service ssh user
      blockinfile:
        path: "{{ ansible_pwd }}/ssh.cfg"
        state: present
        create: true
        mode: 0640
        marker: "{{ tf_core_block_marker }}"
        block: |
          {{ lookup('template', '_tf_core_ssh_cfg.j2') }}
      become: false
      run_once: true
      delegate_to: localhost

- hosts: "{{ lookup('env', 'WORKSPACE') }}_masters:{{ lookup('env', 'WORKSPACE') }}_minions"
  become: false
  gather_facts: true
  tags:
    - route

  tasks:
    - command: >-
        ip route replace default via 192.168.42.1
