---
- name: Gather platform facts
  hosts: "{{ lookup('env', 'HS_WORKSPACE') }}_masters:{{ lookup('env', 'HS_WORKSPACE') }}_minions"
  gather_facts: false
  become: true


  pre_tasks:
    - name: "Wait for ssh to wake up"
      wait_for_connection:
        timeout: 300
        sleep: 10

    - name: Gather facts until private network dhcp occurs
      setup:
      until: ansible_default_ipv4.interface == "ens5"
      retries: 10
      delay: 30

  roles:
    - name: local_resolver

