---
- name: Equip
  hosts: "{{ lookup('env', 'HS_WORKSPACE') }}_platform:!{{ lookup('env', 'HS_WORKSPACE') }}-controller"
  become: true
  gather_facts: true
  tags:
    - base

  roles:
    - name: local_resolver
