---
- hosts: localhost
  become: false
  gather_facts: false

  vars:
    terraform_module: "consul_config"

  pre_tasks:
    - name: Load group vars
      include_vars:
        dir: "{{ workspace_group_vars_dir }}"
        ignore_unknown_extensions: true

  tasks:
    - name: "Copy terraform sources"
      copy:
        src: "{{ project_terraform_dir }}/{{ terraform_module }}"
        dest: "{{ workspace_terraform_dir }}/"
        mode: "u+rwX,g+rX,o-rX"

    - debug:
        msg: >-
          -var consul_address="consul.{{ public_domain }}:{{ consul_api_port }}"
          -var datacenter="{{ workspace }}"
          -var token="{{ root_consul.SecretID }}"
 
    - name: "COMMON - Do Terraform (can take up to 30 minutes)"
      community.general.terraform:
        project_path: "{{ workspace_terraform_dir }}/{{ terraform_module }}"
        state: "{{ (tf_action == 'destroy') | ternary('absent', 'present') }}"
        force_init: true
        workspace: "{{ workspace }}"
        variables:
          consul_address: "consul.{{ public_domain }}:{{ consul_api_port }}"
          datacenter: "{{ workspace }}"
          token: "{{ root_consul.SecretID }}"
      register: tf_result

    - name: Generate host_vars for public_ns
      copy:
        dest: "{{ workspace_secrets_dir }}/tf_consul_config.yml"
        mode: 0600
        content: |-
          ---
          consul_connect_token_server: "{{ tf_result.outputs.consul_acl_nomad_server_token.value }}"
          consul_connect_token_client: "{{ tf_result.outputs.consul_acl_nomad_client_token.value }}"
