---
- hosts: localhost
  become: no
  gather_facts: no

  vars:
    terraform_module: "scw_sandbox"
    terraform_vars:
      public_key_value: "{{ lookup('file', workspace_default_ssh_public_key_file) }}"

    block_marker: >-
      # {mark} -- playbooks/tf_scw_sandbox.yml -- {{ workspace }}

  tasks:
    - import_tasks: "{{ playbook_dir }}/inc/_tf_sanity_checks.yml"

    - name: Include workspace
      include_vars:
        dir: "{{ workspace_group_vars_dir }}"
        ignore_unknown_extensions: yes

    - name: "Copy terraform sources"
      copy:
        src: "{{ project_terraform_dir }}/{{ terraform_module }}"
        dest: "{{ workspace_terraform_dir }}/"

    - name: "COMMON - Do Terraform (can take up to 30 minutes)"
      community.general.terraform:
        project_path: "{{ workspace_terraform_dir }}/{{ terraform_module }}"
        state: "{{ (tf_action == 'destroy') | ternary('absent', 'present') }}"
        force_init: yes
        workspace: "{{ workspace }}"
        variables: "{{ terraform_vars }}"
      register: tf_result


    - name: Generate ready hosts inventory
      blockinfile:
        dest: "{{ ansible_pwd }}/hosts"
        marker: "# {mark}-playbooks/tf_scw_sandbox.yml-{{ workspace }}-ready"
        block: |-
          {{ tf_result.outputs.ansible_inventory.value }}

    - name: Generate ssh config for raw hosts
      blockinfile:
        dest: "{{ ansible_pwd }}/ssh.cfg"
        marker: "# {mark}-playbooks/tf_scw_sandbox.yml-{{ workspace }}-raw_ssh"
        block: |-
          {{ tf_result.outputs.ansible_ssh_cfg.value }}
