---
- hosts: "{{ lookup('env', 'WORKSPACE') }}_masters[0]"
  become: yes
  gather_facts: no

  tasks:
    - uri:
        method: GET
        return_content: yes
        headers:
          X-Consul-Token: "{{ root_consul.SecretID }}"
        url: http://127.0.0.1:8500/v1/agent/connect/ca/roots

    - uri:
        method: GET
        return_content: yes
        headers:
          X-Consul-Token: "{{ root_consul.SecretID }}"
        url: http://127.0.0.1:8500/v1/agent/connect/ca/leaf/web
